# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline conn'
    subscriptionId: 'd4299b9e-f238-4e59-a7cf-e3ea2c35a84e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureRmPipeline -linkedTemplateUri https://raw.githubusercontent.com/luckstar77/AzureRmPipeline/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
